In [291]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split as tts, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [277]:
f = pd.read_csv('/content/Titanic-Dataset.csv')

In [278]:
f.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [279]:
f.isnull().sum()

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [280]:
f.drop(columns = ['PassengerId','Name', 'Ticket', 'Cabin'], inplace = True)

In [281]:
f['Sex'] = f['Sex'].map({'male' : 0, 'female' : 1})
f['Age'] = f['Age'].fillna(f['Age'].median())
f['Embarked'] = f['Embarked'].fillna(f['Embarked'].mode()[0])

In [282]:
f.isnull().sum()

,0
Survived,0
Pclass,0
Sex,0
Age,0
SibSp,0
Parch,0
Fare,0
Embarked,0


In [283]:
f['Embarked'] = f['Embarked'].map({'S' : 0,'C' : 1,'Q' : 2,})

In [284]:
f['FamMem'] = f['Parch'] + f['SibSp']

In [286]:
X = f.drop(columns = ['SibSp', 'Parch','Survived'])
y = f['Survived']

In [287]:
X


,Pclass,Sex,Age,Fare,Embarked,FamMem
0,3,0,22.0,7.2500,0,1
1,1,1,38.0,71.2833,1,1
2,3,1,26.0,7.9250,0,0
3,1,1,35.0,53.1000,0,1
4,3,0,35.0,8.0500,0,0
...,...,...,...,...,...,...
886,2,0,27.0,13.0000,0,0
887,1,1,19.0,30.0000,0,0
888,3,1,28.0,23.4500,0,3
889,1,0,26.0,30.0000,1,0


In [292]:
X_train,X_test, y_train, y_test = tts(X,y,test_size = 0.3, random_state = 2, shuffle = True)

In [293]:
model = LogisticRegression(max_iter= 1000)

In [294]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [295]:
model.coef_,model.intercept_

(array([[-1.15435648e+00,  2.72240120e+00, -4.53151420e-02,
          8.71424553e-04,  1.96795867e-01, -1.93586861e-01]]),
 array([2.38402775]))

In [296]:
y_pred = model.predict(X_test)

In [297]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7910447761194029
[[140  20]
 [ 36  72]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.83       160
           1       0.78      0.67      0.72       108

    accuracy                           0.79       268
   macro avg       0.79      0.77      0.78       268
weighted avg       0.79      0.79      0.79       268



In [298]:
cv_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')
print("CV Accuracy:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

CV Accuracy: [0.78212291 0.79213483 0.78651685 0.78089888 0.8258427 ]
Mean CV Accuracy: 0.7935032326909799
